org.gradle.jvmargs=-Xmx4096M

# This makes it so that fabric/forge modules are only loaded if they are being used.
org.gradle.configureondemand=true

minecraft_version=1.20.1
enabled_platforms=fabric

# Loader Properties
fabric_loader_version=0.15.3

# Mod Properties
mod_version=2.0.0
maven_group=ca.fxco
archives_base_name=rememoryleakfix

# Dependencies
mixinextras_version=0.3.2
